kind: pipeline
name: main

steps:
- name: api
  image: node:10.16.3
  depends_on: [clone]
  environment:
    MONGODB_URI: mongodb://database:27017/db
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
    - cd api
    - npm ci
    - npm test -- --coverage --run-in-band
    - npm run codecov
- name: client
  image: node:10.16.3
  depends_on: [clone]
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
    - cd client
    - npm ci
    - npm test -- --coverage
    - npm run codecov
- name: graphql
  image: node:10.16.3
  depends_on: [clone]
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
    - cd graphql
    - npm ci
    - npm test -- --coverage
    - npm run codecov

services:
  - name: database
    image: mongo

trigger:
  branch:
  - develop
  - master
  - greenkeeper/*