kind: pipeline
name: main

steps:
- name: api
  image: node:10.16.3
  depends_on: [clone]
  environment:
    MONGODB_URI: mongodb://database:27017/db
  commands:
    - cd api
    - npm ci
    - npm test -- --coverage --run-in-band
- name: client
  image: node:10.16.3
  depends_on: [clone]
  commands:
    - cd client
    - npm ci
    - npm test -- --coverage
- name: graphql
  image: node:10.16.3
  depends_on: [clone]
  commands:
    - cd graphql
    - npm ci
    - npm test -- --coverage
- name: codecov
  image: buildpack-deps
  depends_on:
    - api
    - client
    - graphql
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
    - bash -c "bash <(curl https://codecov.io/bash) -f "api/coverage/*" -F api"
    - bash -c "bash <(curl https://codecov.io/bash) -f "client/coverage/*" -F client"
    - bash -c "bash <(curl https://codecov.io/bash) -f "graphql/coverage/*" -F graphql"

services:
  - name: database
    image: mongo

trigger:
  branch:
  - develop
  - master
  - greenkeeper/*