kind: pipeline
name: main

steps:
- name: detect-changed-folders
  image: fmenkes/alpine-git
  commands:
    - scripts/detectChangedFolders.sh
- name: api
  depends_on: [detect-changed-folders]
  image: node:10.16.3
  environment:
    MONGODB_URI: mongodb://database:27017/db
  commands:
    - cd api
    - if ../scripts/shouldNotRun.sh; then exit 0; fi
    - npm install
    - npm test -- --coverage --run-in-band
- name: client
  depends_on: [detect-changed-folders]
  image: node:10.16.3
  commands:
    - cd client
    - if ../scripts/shouldNotRun.sh; then exit 0; fi
    - npm install
    - npm test -- --coverage
- name: graphql-server
  depends_on: [detect-changed-folders]
  image: node:10.16.3
  commands:
    - cd graphql
    - if ../scripts/shouldNotRun.sh; then exit 0; fi
    - npm install
    - npm test -- --coverage
- name: api-codecov
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
      - "*.xml"
    paths:
      - api/coverage
    flags:
      - api
- name: graphql-codecov
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
      - "*.xml"
    paths:
      - graphql/coverage
    flags:
      - graphql
- name: client-codecov
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
      - "*.xml"
    paths:
      - client/coverage
    flags:
      - client

services:
  - name: database
    image: mongo

trigger:
  branch:
  - develop
  - master
  event:
  - push