extends:
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
settings:
  import/resolver:
    node:
      extensions: [".d.ts"]
rules:
  prettier/prettier:
    - error
  "@typescript-eslint/explicit-function-return-type": "off"
env:
  jest: true