coverage:
  status:
    project:
      default:
        target: 90%
        threshold: null
      api:
        flags: api
        target: 90%
      graphql:
        flags: graphql
        target: 90%
      client:
        flags: client
        target: 90%
flags:
  client:
    paths:
      - client/
  graphql:
    paths:
      - graphql/
  api:
    paths:
      - api/