coverage:
  status:
    project:
      default:
        target: 90%
      api:
        flags: api
        target: 90%
      graphql:
        flags: graphql
        target: 90%
      client:
        flags: client
        target: 90%
flags:
  client:
    paths:
      - client/src
  graphql:
    paths:
      - graphql/src
  api:
    paths:
      - api/src