version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: development.Dockerfile
    command: concurrently "npm start -- --host=0.0.0.0" "onchange -v package-lock.json -- npm i --no-shrinkwrap"
    container_name: mngrka-client
    restart: on-failure
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REACT_APP_GRAPHQL_URI=http://localhost:4000
    ports:
      - '3000:3000'
    volumes:
      - ./node_modules:/usr/src/node_modules
      - .eslintrc.yaml:/usr/src/.eslintrc.yaml
      - .prettierrc.yaml:/usr/src/.prettierrc.yaml
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
  graphql:
    build: ./graphql
    container_name: mngrka-graphql
    restart: on-failure
    environment:
      NODE_ENV: development
      KOA_API_URL: http://api:8765
    ports:
      - '4000:4000'
    volumes:
      - ./graphql:/home/node/app
      - /home/node/app/node_modules
  api:
    build: ./api
    container_name: mngrka-api
    restart: on-failure
    environment: 
      NODE_ENV: development
      MONGODB_URI: mongodb://database:27017/mngrka
      PORT: 8765
    depends_on:
      - database
    ports:
      - '8765:8765'
    volumes: 
      - ./api:/home/node/app
      - /home/node/app/node_modules
  database:
    image: mongo
    container_name: mngrka-db
    restart: on-failure
    ports:
      - '27017:27017'
    volumes:
      - data-volume:/data/db

volumes:
  data-volume: